/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CompAereaController;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.CompAereaModel;
/**
 *
 * @author simoe
 */
public final class CadCompAereaView extends javax.swing.JFrame {

    /**
     * Creates new form CompAereaView
     */
    public CadCompAereaView() {
        initComponents();
        
        txtCodigo.setText("");
        txtCompAerea.setText("");
        chkSituacao.setSelected(false);
        alteraBotoes(true,false,false,false);
        txtCodigo.setEnabled(true);
        txtCompAerea.setEnabled(false);
        chkSituacao.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCompAerea = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnProcurar = new javax.swing.JToggleButton();
        chkSituacao = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Compania Aerea");

        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });

        jLabel2.setText("Código:");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnProcurar.setText("Procurar");
        btnProcurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProcurarMouseClicked(evt);
            }
        });
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });

        chkSituacao.setText("Ativo");
        chkSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSituacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(320, 320, 320))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCompAerea, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProcurar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkSituacao)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnProcurar)
                    .addComponent(chkSituacao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCompAerea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void alteraBotoes(boolean novo,boolean excluir,boolean cancelar,boolean salvar){
        btnNovo.setEnabled(novo);
        btnCancelar.setEnabled(cancelar);
        btnSalvar.setEnabled(salvar);
        btnExcluir.setEnabled(excluir);
    }    
    
    
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        try{
            alteraBotoes(false,true,true,true);
            btnProcurar.setEnabled(false);
            txtCodigo.setText("");
            txtCompAerea.setText("");
            chkSituacao.setSelected(true);
            txtCodigo.setEnabled(true);
            txtCompAerea.setEnabled(true);
            chkSituacao.setEnabled(true);

            CompAereaController objCompAerea = new CompAereaController();
            ResultSet rsCompAerea = objCompAerea.buscaUltimaCompAerea();

            if (rsCompAerea.next()){
                txtCodigo.setText(rsCompAerea.getString("lastCod"));
                txtCodigo.setEnabled(false);
                txtCompAerea.setFocusable(true);
            }else{

            }
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "CadCompAereaView: " + erro);
        }
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
      
        CompAereaController controle = new CompAereaController();
        
        if(controle.excluiCompAerea(Integer.parseInt(txtCodigo.getText()))){
            JOptionPane.showMessageDialog(null, "Compania Aérea excluída!");
            alteraBotoes(true,false,false,false);
            txtCodigo.setText("");
            txtCompAerea.setText("");
            chkSituacao.setSelected(false);
            txtCodigo.setEnabled(true);
            txtCompAerea.setEnabled(false);
            chkSituacao.setEnabled(false);
        } else{
            JOptionPane.showMessageDialog(this, "Erro ao excluir!");
        }
        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        alteraBotoes(true,false,false,false);
        txtCodigo.setText("");
        txtCompAerea.setText("");
        chkSituacao.setSelected(false);
        txtCodigo.setEnabled(true);
        txtCompAerea.setEnabled(false);
        chkSituacao.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        if (txtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o Código da Compania Aérea!");
            return;
        }
        
        if (txtCompAerea.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o Nome da Compania Aérea!");
            return;
        }
        
        int status;
        
        CompAereaModel compAerea = new CompAereaModel();
        
        compAerea.setCodCompAerea(Integer.parseInt(txtCodigo.getText()));
        compAerea.setCompAerea(txtCompAerea.getText());
        
        if (chkSituacao.isSelected()) {
            status = 1;
        } else {
            status = 0;
        }
        
        compAerea.setSituacao(status);
        
        CompAereaController controle = new CompAereaController();
        
        if(controle.cadastraCompAerea(compAerea)){
            JOptionPane.showMessageDialog(null, "Compania Aérea cadastrado!");
            alteraBotoes(true,false,false,false);
            txtCodigo.setText("");
            txtCompAerea.setText("");
            chkSituacao.setSelected(false);
            txtCodigo.setEnabled(true);
            txtCompAerea.setEnabled(false);
            chkSituacao.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar!");
        } 
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnProcurarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcurarMouseClicked

    }//GEN-LAST:event_btnProcurarMouseClicked

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed

    }//GEN-LAST:event_btnProcurarActionPerformed

    private void chkSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSituacaoActionPerformed

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
        
        CompAereaController controle = new CompAereaController();

        if (!txtCodigo.getText().isEmpty()){
            try {
                ResultSet rs = controle.buscaCompAerea(txtCodigo.getText());
                if(rs.next()){
                    txtCodigo.setText(rs.getString("idCompAerea"));
                    if (rs.getString("situacao") == "1"){
                        chkSituacao.setSelected(true);
                    }else{
                        chkSituacao.setSelected(false);
                    }
                    
                    txtCompAerea.setText(rs.getString("descricao"));
                    alteraBotoes(false,true,true,true);
                    txtCodigo.setEnabled(true);
                    txtCompAerea.setEnabled(true);
                    chkSituacao.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(this, "Compania Aeronave não encontrado!");
                    txtCodigo.setText("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao pesquisar a compania aérea!");
                txtCodigo.setText("");
            }
        }else{
            return;
        }
    }//GEN-LAST:event_txtCodigoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCompAereaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCompAereaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCompAereaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCompAereaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCompAereaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JToggleButton btnProcurar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCompAerea;
    // End of variables declaration//GEN-END:variables
}
