/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.LoginModel;
import controller.UsuarioController;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author simoe
 */
public class CadUserView extends javax.swing.JFrame {

    /**
     * Creates new form CadUserView
     */
    public CadUserView() throws SQLException {
        initComponents();
        
        limpaCampos();
        alteraBotoes(true,false,false,false);
        txtCodUsuario.setEnabled(true);
        txtNomeUsuario.setEnabled(false);
        txtUsuario.setEnabled(false);
        txtSenha.setEnabled(false);
        cbCompAerea.setEnabled(false);
        cbPerfilUsuario.setEnabled(false);
        chkSituacao.setEnabled(false);
        
        UsuarioController cac = new UsuarioController();
        
        List<String> listCompAerea = new ArrayList<>();
        List<String> listPerfilUsuario = new ArrayList<>();
        
        listPerfilUsuario.add("Administrador");
        listPerfilUsuario.add("Comum");
        listPerfilUsuario.add("Supervisor");

        
        cac.buscaCompAerea(listCompAerea);
        
        DefaultComboBoxModel companiaaerea = new DefaultComboBoxModel(listCompAerea.toArray());
        cbCompAerea.setModel(companiaaerea);
        
        DefaultComboBoxModel perfilusuario = new DefaultComboBoxModel(listPerfilUsuario.toArray());
        cbPerfilUsuario.setModel(perfilusuario);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        nameUser = new javax.swing.JLabel();
        txtCodUsuario = new javax.swing.JTextField();
        btnProcurar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbCompAerea = new javax.swing.JComboBox<>();
        chkSituacao = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cbPerfilUsuario = new javax.swing.JComboBox<>();
        txtSenha = new javax.swing.JPasswordField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuários");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(500, 500));
        setResizable(false);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        nameUser.setText("Cód do Usuário:");

        txtCodUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodUsuarioFocusLost(evt);
            }
        });
        txtCodUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodUsuarioActionPerformed(evt);
            }
        });

        btnProcurar.setText("Procurar");
        btnProcurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProcurarMouseClicked(evt);
            }
        });
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome Completo:");

        jLabel2.setText("Usuário");

        jLabel3.setText("Senha:");

        jLabel4.setText("Companhia Aérea:");

        chkSituacao.setText("Ativo");

        jLabel5.setText("Perfil de Usuário:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(nameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProcurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkSituacao))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbPerfilUsuario, 0, 314, Short.MAX_VALUE)
                            .addComponent(cbCompAerea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNomeUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSenha)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkSituacao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameUser)
                        .addComponent(txtCodUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProcurar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCompAerea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPerfilUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        try{
            
            limpaCampos();
            alteraBotoes(false,true,true,true);
            btnProcurar.setEnabled(false);
            txtCodUsuario.setEnabled(false);
            txtNomeUsuario.setEnabled(true);
            txtUsuario.setEnabled(true);
            txtSenha.setEnabled(true);
            cbCompAerea.setEnabled(true);
            cbPerfilUsuario.setEnabled(true);
            chkSituacao.setEnabled(true);
        
            UsuarioController objUsuarioConexao = new UsuarioController();
            ResultSet rsUsuarioConexao = objUsuarioConexao.buscaUltimoUsuario();
            if(rsUsuarioConexao.next()){
                txtCodUsuario.setText(rsUsuarioConexao.getString("lastCod"));
                txtCodUsuario.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao criar novo usuário!");
            }
        }catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "CadUserView: " + erro);
        } 
    }//GEN-LAST:event_btnNovoActionPerformed
    
    public void alteraBotoes(boolean novo,boolean excluir,boolean cancelar,boolean salvar){
        btnNovo.setEnabled(novo);
        btnCancelar.setEnabled(cancelar);
        btnSalvar.setEnabled(salvar);
        btnExcluir.setEnabled(excluir);
    }
    
    public void limpaCampos(){
        txtCodUsuario.setText("");
        txtNomeUsuario.setText("");
        txtUsuario.setText("");
        txtSenha.setText("");
    }
    
    
    
    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void txtCodUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodUsuarioActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        int status;
        
        if (txtCodUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o Código de Usuário!");
            return;
        }
        
        if (txtNomeUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o Nome do Usuário!");
            return;
        }
        
        if (txtUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe o Usuário!");
            return;
        }
        
        if (txtSenha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe a Senha!");
            return;
        }
        
        if (cbCompAerea.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Informe a Companhia Aérea!");
            return;
        }
        
        if (cbPerfilUsuario.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Informe o Tipo do Perfil de Usuário!");
            return;
        }

        
        alteraBotoes(false,false,true,true);
        
        LoginModel Usuario = new LoginModel();
        
        Usuario.setIdLogin(Integer.parseInt(txtCodUsuario.getText()));
        Usuario.setNameUser(txtNomeUsuario.getText());
        Usuario.setPassword(txtSenha.getText());
        Usuario.setPerfilUsuario(cbPerfilUsuario.getSelectedIndex());
        Usuario.setUser(txtUsuario.getText());
        Usuario.setCompAerea(cbCompAerea.getSelectedIndex());
        if (chkSituacao.isSelected()) {
            status = 1;
        } else {
            status = 0;
        }  
        Usuario.setSituacao(status);
        
        UsuarioController controle = new UsuarioController();
        
        if(controle.cadastraUsuario(Usuario)){
            JOptionPane.showMessageDialog(null, "Usuário cadastrado!");
            limpaCampos();
            alteraBotoes(true,false,false,false);
            txtCodUsuario.setEnabled(true);
            txtNomeUsuario.setEnabled(false);
            txtUsuario.setEnabled(false);
            txtSenha.setEnabled(false);
            cbCompAerea.setEnabled(false);
            cbPerfilUsuario.setEnabled(false);
            chkSituacao.setEnabled(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar!");
        }
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaCampos();
        alteraBotoes(true,false,false,false);
        txtCodUsuario.setEnabled(true);
        txtNomeUsuario.setEnabled(false);
        txtUsuario.setEnabled(false);
        txtSenha.setEnabled(false);
        cbCompAerea.setEnabled(false);
        cbPerfilUsuario.setEnabled(false);
        chkSituacao.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCodUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodUsuarioFocusLost
        
        UsuarioController controle = new UsuarioController();
        
        
       
        if (!txtCodUsuario.getText().isEmpty()){
            try {
                ResultSet rs = controle.buscaUsuario(Integer.parseInt(txtCodUsuario.getText()));
                if(rs.next()){
                    txtCodUsuario.setText(rs.getString("idUser"));
                    if (rs.getString("situacao") == "1"){
                        chkSituacao.setSelected(true);
                    }else{
                        chkSituacao.setSelected(false);
                    }
                    txtNomeUsuario.setText(rs.getString("nameuser"));
                    txtUsuario.setText(rs.getString("user"));
                    txtSenha.setText(rs.getString("password"));
                    cbCompAerea.setSelectedIndex(rs.getInt("compAerea"));
                    cbPerfilUsuario.setSelectedIndex(rs.getInt("perfil"));

                    alteraBotoes(false,true,true,true);
                    txtCodUsuario.setEnabled(true);
                    txtNomeUsuario.setEnabled(true);
                    txtUsuario.setEnabled(true);
                    txtSenha.setEnabled(true);
                    cbCompAerea.setEnabled(true);
                    cbPerfilUsuario.setEnabled(true);
                    chkSituacao.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(this, "Usuário não encontrado!");
                    txtCodUsuario.setText("");
                    txtNomeUsuario.setText("");
                    txtUsuario.setText("");
                    txtSenha.setText("");
                    cbCompAerea.setSelectedIndex(-1);
                    cbPerfilUsuario.setSelectedIndex(-1);
                    chkSituacao.setSelected(false);
                    txtCodUsuario.setFocusable(true);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao pesquisar usuário!");
            }
        }else{
            return;
        }
    }//GEN-LAST:event_txtCodUsuarioFocusLost

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        UsuarioController controle = new UsuarioController();
        
        if(controle.excluiUsuario(Integer.parseInt(txtCodUsuario.getText()))){
            JOptionPane.showMessageDialog(null, "Usuário excluido!");
            limpaCampos();
            alteraBotoes(true,false,false,false);
            txtCodUsuario.setEnabled(true);
            txtNomeUsuario.setEnabled(true);
            txtUsuario.setEnabled(true);
            txtSenha.setEnabled(true);
            cbCompAerea.setEnabled(true);
            cbPerfilUsuario.setEnabled(true);
            chkSituacao.setEnabled(true);
        } else{
            JOptionPane.showMessageDialog(this, "Erro ao excluir!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnProcurarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcurarMouseClicked

    }//GEN-LAST:event_btnProcurarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadUserView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CadUserView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JToggleButton btnProcurar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbCompAerea;
    private javax.swing.JComboBox<String> cbPerfilUsuario;
    private javax.swing.JCheckBox chkSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nameUser;
    private javax.swing.JTextField txtCodUsuario;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
